language: python
python:
  - "2.6"
  - "2.7"

before_install:
  - sudo apt-get purge -y libpq-dev
  - sudo apt-get install -y postgresql-9.3 postgresql-server-dev-9.3

install:
  - pip install -r requirements-dev.txt

script:
  - make test
