#!/usr/bin/python
"""
Entry point for collecting logs and config information about InsightIQ
for remote troubleshooting.
"""
import sys

from iiqtools.iiq_gather_info import main


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
