#!/usr/bin/python
"""
Entry point for displaying the installed versions of InsightIQ and IIQTools
"""
import sys

from iiqtools.iiq_version import main


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
