#!/opt/rh/python27/root/usr/bin/python
"""
Entry point for displaying the installed versions of InsightIQ and IIQTools
"""
import sys

from iiqtools.iiqtools_version import main


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
