#!/opt/rh/python27/root/usr/bin/python
"""
Entry point for converting a cluster export from tar to zip format
"""
import sys

from iiqtools.iiqtools_tar_to_zip import main


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
