#!/opt/rh/python27/root/usr/bin/python
"""
Entry point for installing/uninstall patches for InsightIQ.
"""
import sys

from iiqtools.iiqtools_patch import main


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
